# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'I Bike CPH' do
pod 'HockeySDK'
pod 'Facebook-iOS-SDK'
pod 'GoogleAnalytics-iOS-SDK', '3.0.3c'
end

